### ISSUE TITLE
Objectives need a notion of a "Set Name"

### ISSUE THREAD

**Issue by wwall3r** [wwall3r/bingo#7]
This could be a particular database table/association, or it could potentially just be a special tag like "title: Set Name". I think the advantage to the former is that you could more easily constrain them to be unique values.

The goal is to be able to present, as far as the "objective set selection" (either for a new/existing game, for admin purposes, etc.). That selection should contain a way of saying "I like this objective, so show me the entire set from whence it came" in addition to "Add all from this set" and "search by set name"

**Comment by jaystile** [comment]
I think a new table 'objective_set' and an association table from 'objective_set' to 'objectives' would satisfy this need. It would allow for pre-bundled collections of objectives. Intially, the concept was to use 'Tags' to filter. This starts to blow up a little bit when we need to consider who owns the objective-sets and how are they modified. The use cases need to be defined.

**Comment by wwall3r** [comment]
> It might be worth pulling out the objectives association from the game to an 'objective set'

This I would like to avoid. If I search for something like "Drinking Games," I should be able to add objectives from more than one set to my game. What the Objective Set gives you is the ability to add all the objectives from that set. Then you can potentially add another set or ad hoc add/remove a few individual objectives.

**Comment by jaystile** [comment]
Started a wiki: https://github.com/wwall3r/bingo/wiki/Issue-%237
